sudo: false
language: python
branches:
  only: master
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  # - "pypy3"
matrix:
  allow_failures:
    - "2.6"
    - "nightly"
    - "pypy"
    # - "pypy3"
  fast_finish: true
cache: pip
install:
  - pip install -U setuptools
  - pip install tox-travis
script: tox --skip-missing-interpreters
